'use strict';

/**
 * Seed completo e generoso para testes de toda a API.
 *
 * Credenciais principais:
 * - owner@restaurante.com   / Owner@123
 * - manager@restaurante.com / Manager@123
 * - cliente@example.com     / Cliente@123
 * - admin@example.com       / Admin@123
 *
 * @param {import('knex').Knex} knex
 */

const bcrypt = require('bcrypt');

exports.seed = async function (knex) {
  const now = new Date('2026-05-14T12:00:00.000Z');

  // Limpa tudo na ordem segura para FK
  const tables = [
    'order_reviews',
    'restaurant_reviews',
    'favorites',
    'coupon_redemptions',
    'payments',
    'order_item_addons',
    'order_items',
    'orders',
    'cart_item_addons',
    'cart_items',
    'carts',
    'combo_items',
    'combos',
    'product_addon_groups',
    'addons',
    'addon_groups',
    'product_images',
    'products',
    'categories',
    'delivery_zones',
    'restaurant_addresses',
    'operating_hours',
    'restaurant_users',
    'coupons',
    'restaurants',
    'user_addresses',
    'addresses',
    'password_reset_tokens',
    'refresh_tokens',
    'user_auth_providers',
    'users',
  ];

  await knex.raw('SET FOREIGN_KEY_CHECKS = 0');
  for (const tableName of tables) {
    await knex(tableName).del();
  }
  await knex.raw('SET FOREIGN_KEY_CHECKS = 1');

  const [
    customerHash,
    ownerHash,
    managerHash,
    attendantHash,
    kitchenHash,
    courierHash,
    financeHash,
    adminHash,
  ] = await Promise.all([
    bcrypt.hash('Cliente@123', 10),
    bcrypt.hash('Owner@123', 10),
    bcrypt.hash('Manager@123', 10),
    bcrypt.hash('Attendant@123', 10),
    bcrypt.hash('Kitchen@123', 10),
    bcrypt.hash('Courier@123', 10),
    bcrypt.hash('Finance@123', 10),
    bcrypt.hash('Admin@123', 10),
  ]);

  await knex('users').insert([
    {
      id: 1,
      first_name: 'Cliente',
      last_name: 'Teste',
      email: 'cliente@example.com',
      phone: '+55 11 98888-0001',
      birth_date: '1995-04-10',
      user_type: 'customer',
      status: 'active',
      is_email_verified: 1,
      is_phone_verified: 1,
      last_login_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: 2,
      first_name: 'Ana',
      last_name: 'Oliveira',
      email: 'ana.cliente@example.com',
      phone: '+55 11 98888-0002',
      birth_date: '1993-02-18',
      user_type: 'customer',
      status: 'active',
      is_email_verified: 1,
      is_phone_verified: 0,
      last_login_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: 3,
      first_name: 'Bruno',
      last_name: 'Silva',
      email: 'bruno.cliente@example.com',
      phone: '+55 11 98888-0003',
      birth_date: '1989-08-03',
      user_type: 'customer',
      status: 'active',
      is_email_verified: 1,
      is_phone_verified: 1,
      last_login_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: 4,
      first_name: 'Carla',
      last_name: 'Mendes',
      email: 'carla.cliente@example.com',
      phone: '+55 11 98888-0004',
      birth_date: '1991-11-27',
      user_type: 'customer',
      status: 'active',
      is_email_verified: 1,
      is_phone_verified: 1,
      last_login_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: 5,
      first_name: 'Diego',
      last_name: 'Souza',
      email: 'diego.cliente@example.com',
      phone: '+55 11 98888-0005',
      birth_date: '1998-06-09',
      user_type: 'customer',
      status: 'pending_verification',
      is_email_verified: 0,
      is_phone_verified: 0,
      created_at: now,
      updated_at: now,
    },
    {
      id: 6,
      first_name: 'Elisa',
      last_name: 'Campos',
      email: 'elisa.cliente@example.com',
      phone: '+55 11 98888-0006',
      birth_date: '1990-01-14',
      user_type: 'customer',
      status: 'inactive',
      is_email_verified: 1,
      is_phone_verified: 0,
      created_at: now,
      updated_at: now,
    },
    {
      id: 7,
      first_name: 'Otavio',
      last_name: 'Dono',
      email: 'owner@restaurante.com',
      phone: '+55 11 97777-0007',
      birth_date: '1987-03-01',
      user_type: 'restaurant_staff',
      status: 'active',
      is_email_verified: 1,
      is_phone_verified: 1,
      last_login_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: 8,
      first_name: 'Marina',
      last_name: 'Gerente',
      email: 'manager@restaurante.com',
      phone: '+55 11 97777-0008',
      birth_date: '1988-07-22',
      user_type: 'restaurant_staff',
      status: 'active',
      is_email_verified: 1,
      is_phone_verified: 1,
      last_login_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: 9,
      first_name: 'Paulo',
      last_name: 'Atendente',
      email: 'attendant@restaurante.com',
      phone: '+55 11 97777-0009',
      birth_date: '1992-12-13',
      user_type: 'restaurant_staff',
      status: 'active',
      is_email_verified: 1,
      is_phone_verified: 1,
      last_login_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: 10,
      first_name: 'Roberta',
      last_name: 'Cozinha',
      email: 'kitchen@restaurante.com',
      phone: '+55 11 97777-0010',
      birth_date: '1994-09-30',
      user_type: 'restaurant_staff',
      status: 'active',
      is_email_verified: 1,
      is_phone_verified: 0,
      created_at: now,
      updated_at: now,
    },
    {
      id: 11,
      first_name: 'Caio',
      last_name: 'Entrega',
      email: 'courier@restaurante.com',
      phone: '+55 11 97777-0011',
      birth_date: '1996-04-05',
      user_type: 'restaurant_staff',
      status: 'active',
      is_email_verified: 1,
      is_phone_verified: 1,
      created_at: now,
      updated_at: now,
    },
    {
      id: 12,
      first_name: 'Fabio',
      last_name: 'Financeiro',
      email: 'finance@restaurante.com',
      phone: '+55 11 97777-0012',
      birth_date: '1986-10-20',
      user_type: 'restaurant_staff',
      status: 'active',
      is_email_verified: 1,
      is_phone_verified: 1,
      created_at: now,
      updated_at: now,
    },
    {
      id: 13,
      first_name: 'Admin',
      last_name: 'Plataforma',
      email: 'admin@example.com',
      phone: '+55 11 96666-0013',
      birth_date: '1985-05-15',
      user_type: 'platform_admin',
      status: 'active',
      is_email_verified: 1,
      is_phone_verified: 1,
      last_login_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: 14,
      first_name: 'Gabriela',
      last_name: 'Google',
      email: 'gabriela.oauth@example.com',
      phone: '+55 11 95555-0014',
      birth_date: '1997-01-11',
      user_type: 'customer',
      status: 'active',
      is_email_verified: 1,
      is_phone_verified: 0,
      created_at: now,
      updated_at: now,
    },
    {
      id: 15,
      first_name: 'Miguel',
      last_name: 'Microsoft',
      email: 'miguel.oauth@example.com',
      phone: '+55 11 95555-0015',
      birth_date: '1994-03-08',
      user_type: 'customer',
      status: 'active',
      is_email_verified: 1,
      is_phone_verified: 0,
      created_at: now,
      updated_at: now,
    },
  ]);

  await knex('user_auth_providers').insert([
    { id: 1, user_id: 1, provider: 'local', password_hash: customerHash, is_primary: 1, last_used_at: now, created_at: now, updated_at: now },
    { id: 2, user_id: 2, provider: 'local', password_hash: customerHash, is_primary: 1, last_used_at: now, created_at: now, updated_at: now },
    { id: 3, user_id: 3, provider: 'local', password_hash: customerHash, is_primary: 1, last_used_at: now, created_at: now, updated_at: now },
    { id: 4, user_id: 4, provider: 'local', password_hash: customerHash, is_primary: 1, last_used_at: now, created_at: now, updated_at: now },
    { id: 5, user_id: 5, provider: 'local', password_hash: customerHash, is_primary: 1, created_at: now, updated_at: now },
    { id: 6, user_id: 6, provider: 'local', password_hash: customerHash, is_primary: 1, created_at: now, updated_at: now },
    { id: 7, user_id: 7, provider: 'local', password_hash: ownerHash, is_primary: 1, last_used_at: now, created_at: now, updated_at: now },
    { id: 8, user_id: 8, provider: 'local', password_hash: managerHash, is_primary: 1, last_used_at: now, created_at: now, updated_at: now },
    { id: 9, user_id: 9, provider: 'local', password_hash: attendantHash, is_primary: 1, last_used_at: now, created_at: now, updated_at: now },
    { id: 10, user_id: 10, provider: 'local', password_hash: kitchenHash, is_primary: 1, created_at: now, updated_at: now },
    { id: 11, user_id: 11, provider: 'local', password_hash: courierHash, is_primary: 1, created_at: now, updated_at: now },
    { id: 12, user_id: 12, provider: 'local', password_hash: financeHash, is_primary: 1, created_at: now, updated_at: now },
    { id: 13, user_id: 13, provider: 'local', password_hash: adminHash, is_primary: 1, last_used_at: now, created_at: now, updated_at: now },
    {
      id: 14,
      user_id: 14,
      provider: 'google',
      provider_user_id: 'google-uid-14',
      is_primary: 1,
      last_used_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: 15,
      user_id: 15,
      provider: 'microsoft',
      provider_user_id: 'ms-uid-15',
      is_primary: 1,
      last_used_at: now,
      created_at: now,
      updated_at: now,
    },
  ]);

  await knex('refresh_tokens').insert([
    { id: 1, user_id: 1, token_hash: 'rt_hash_customer_1', user_agent: 'Insomnia', ip_address: '127.0.0.1', expires_at: new Date('2026-12-31T23:59:59.000Z'), created_at: now, updated_at: now },
    { id: 2, user_id: 7, token_hash: 'rt_hash_owner_7', user_agent: 'Insomnia', ip_address: '127.0.0.1', expires_at: new Date('2026-12-31T23:59:59.000Z'), created_at: now, updated_at: now },
    { id: 3, user_id: 8, token_hash: 'rt_hash_manager_8', user_agent: 'Insomnia', ip_address: '127.0.0.1', expires_at: new Date('2026-12-31T23:59:59.000Z'), created_at: now, updated_at: now },
    { id: 4, user_id: 13, token_hash: 'rt_hash_admin_13', user_agent: 'Insomnia', ip_address: '127.0.0.1', expires_at: new Date('2026-12-31T23:59:59.000Z'), created_at: now, updated_at: now },
  ]);

  await knex('password_reset_tokens').insert([
    { id: 1, user_id: 1, token_hash: 'pr_hash_customer_1', expires_at: new Date('2026-12-31T23:59:59.000Z'), created_at: now, updated_at: now },
    { id: 2, user_id: 5, token_hash: 'pr_hash_customer_5', expires_at: new Date('2026-12-31T23:59:59.000Z'), created_at: now, updated_at: now },
  ]);

  await knex('addresses').insert([
    { id: 1, zip_code: '01310-100', street: 'Avenida Paulista', number: '1000', complement: 'Apto 12', neighborhood: 'Bela Vista', city: 'Sao Paulo', state: 'SP', country: 'Brazil', latitude: -23.561684, longitude: -46.656139, created_at: now, updated_at: now },
    { id: 2, zip_code: '05422-000', street: 'Rua Teodoro Sampaio', number: '1500', neighborhood: 'Pinheiros', city: 'Sao Paulo', state: 'SP', country: 'Brazil', latitude: -23.558495, longitude: -46.683899, created_at: now, updated_at: now },
    { id: 3, zip_code: '04038-001', street: 'Rua Domingos de Morais', number: '2155', neighborhood: 'Vila Mariana', city: 'Sao Paulo', state: 'SP', country: 'Brazil', latitude: -23.589841, longitude: -46.634973, created_at: now, updated_at: now },
    { id: 4, zip_code: '01001-000', street: 'Praca da Se', number: '100', neighborhood: 'Se', city: 'Sao Paulo', state: 'SP', country: 'Brazil', created_at: now, updated_at: now },
    { id: 5, zip_code: '20040-010', street: 'Rua da Assembleia', number: '88', neighborhood: 'Centro', city: 'Rio de Janeiro', state: 'RJ', country: 'Brazil', created_at: now, updated_at: now },
    { id: 6, zip_code: '30140-071', street: 'Avenida Afonso Pena', number: '1200', neighborhood: 'Centro', city: 'Belo Horizonte', state: 'MG', country: 'Brazil', created_at: now, updated_at: now },
    { id: 7, zip_code: '01311-000', street: 'Rua Augusta', number: '650', neighborhood: 'Consolacao', city: 'Sao Paulo', state: 'SP', country: 'Brazil', created_at: now, updated_at: now },
    { id: 8, zip_code: '04567-000', street: 'Avenida Engenheiro Luis Carlos Berrini', number: '1100', neighborhood: 'Brooklin', city: 'Sao Paulo', state: 'SP', country: 'Brazil', created_at: now, updated_at: now },
    { id: 9, zip_code: '22290-240', street: 'Rua Voluntarios da Patria', number: '321', neighborhood: 'Botafogo', city: 'Rio de Janeiro', state: 'RJ', country: 'Brazil', created_at: now, updated_at: now },
    { id: 10, zip_code: '30112-000', street: 'Rua da Bahia', number: '700', neighborhood: 'Lourdes', city: 'Belo Horizonte', state: 'MG', country: 'Brazil', created_at: now, updated_at: now },
    { id: 11, zip_code: '05409-000', street: 'Rua dos Pinheiros', number: '700', neighborhood: 'Pinheiros', city: 'Sao Paulo', state: 'SP', country: 'Brazil', created_at: now, updated_at: now },
    { id: 12, zip_code: '88010-000', street: 'Rua Felipe Schmidt', number: '500', neighborhood: 'Centro', city: 'Florianopolis', state: 'SC', country: 'Brazil', created_at: now, updated_at: now },
  ]);

  await knex('user_addresses').insert([
    { id: 1, user_id: 1, address_id: 1, label: 'Home', is_default: 1, reference_note: 'Portaria azul', created_at: now, updated_at: now },
    { id: 2, user_id: 1, address_id: 2, label: 'Work', is_default: 0, created_at: now, updated_at: now },
    { id: 3, user_id: 2, address_id: 3, label: 'Home', is_default: 1, created_at: now, updated_at: now },
    { id: 4, user_id: 3, address_id: 4, label: 'Home', is_default: 1, created_at: now, updated_at: now },
    { id: 5, user_id: 4, address_id: 5, label: 'Casa da Praia', is_default: 1, created_at: now, updated_at: now },
    { id: 6, user_id: 5, address_id: 6, label: 'Home', is_default: 1, created_at: now, updated_at: now },
  ]);

  await knex('restaurants').insert([
    {
      id: 1,
      slug: 'demo-burgers',
      subdomain: 'restaurante01',
      legal_name: 'Demo Burgers LTDA',
      trade_name: 'Demo Burgers',
      document_number: '12.345.678/0001-10',
      support_phone: '+55 11 96666-1001',
      support_email: 'contato@demoburgers.com',
      logo_url: 'https://picsum.photos/200?burger',
      banner_url: 'https://picsum.photos/1200/300?burger',
      description: 'Hamburgueria artesanal com ingredientes premium.',
      status: 'active',
      is_open: 1,
      minimum_order_value: 20,
      base_delivery_fee: 6.5,
      avg_preparation_time_min: 30,
      accepts_pickup: 1,
      accepts_delivery: 1,
      created_at: now,
      updated_at: now,
    },
    {
      id: 2,
      slug: 'sushi-prime',
      subdomain: 'restaurante02',
      legal_name: 'Sushi Prime Alimentacao LTDA',
      trade_name: 'Sushi Prime',
      document_number: '22.333.444/0001-20',
      support_phone: '+55 21 95555-1002',
      support_email: 'atendimento@sushiprime.com',
      logo_url: 'https://picsum.photos/200?sushi',
      banner_url: 'https://picsum.photos/1200/300?sushi',
      description: 'Comida japonesa contemporanea.',
      status: 'active',
      is_open: 1,
      minimum_order_value: 35,
      base_delivery_fee: 8,
      avg_preparation_time_min: 40,
      accepts_pickup: 1,
      accepts_delivery: 1,
      created_at: now,
      updated_at: now,
    },
    {
      id: 3,
      slug: 'pizza-estacao',
      subdomain: 'restaurante03',
      legal_name: 'Pizzaria Estacao LTDA',
      trade_name: 'Pizza Estacao',
      document_number: '33.222.111/0001-30',
      support_phone: '+55 31 94444-1003',
      support_email: 'suporte@pizzaestacao.com',
      logo_url: 'https://picsum.photos/200?pizza',
      banner_url: 'https://picsum.photos/1200/300?pizza',
      description: 'Pizzas classicas e especiais no forno a lenha.',
      status: 'temporarily_closed',
      is_open: 0,
      minimum_order_value: 25,
      base_delivery_fee: 7,
      avg_preparation_time_min: 35,
      accepts_pickup: 1,
      accepts_delivery: 1,
      created_at: now,
      updated_at: now,
    },
  ]);

  await knex('restaurant_users').insert([
    { id: 1, restaurant_id: 1, user_id: 7, role: 'owner', is_active: 1, created_at: now, updated_at: now },
    { id: 2, restaurant_id: 1, user_id: 8, role: 'manager', is_active: 1, created_at: now, updated_at: now },
    { id: 3, restaurant_id: 1, user_id: 9, role: 'attendant', is_active: 1, created_at: now, updated_at: now },
    { id: 4, restaurant_id: 1, user_id: 10, role: 'kitchen', is_active: 1, created_at: now, updated_at: now },
    { id: 5, restaurant_id: 1, user_id: 11, role: 'courier', is_active: 1, created_at: now, updated_at: now },
    { id: 6, restaurant_id: 1, user_id: 12, role: 'finance', is_active: 1, created_at: now, updated_at: now },
    { id: 7, restaurant_id: 2, user_id: 8, role: 'owner', is_active: 1, created_at: now, updated_at: now },
    { id: 8, restaurant_id: 2, user_id: 9, role: 'manager', is_active: 1, created_at: now, updated_at: now },
    { id: 9, restaurant_id: 3, user_id: 7, role: 'owner', is_active: 1, created_at: now, updated_at: now },
  ]);

  const operatingHours = [];
  let operatingHourId = 1;
  for (const restaurantId of [1, 2, 3]) {
    for (let weekday = 0; weekday <= 6; weekday += 1) {
      const isClosed = weekday === 1 && restaurantId === 3;
      operatingHours.push({
        id: operatingHourId,
        restaurant_id: restaurantId,
        weekday,
        shift_index: 1,
        opens_at: isClosed ? null : '11:00:00',
        closes_at: isClosed ? null : (restaurantId === 2 ? '23:00:00' : '22:00:00'),
        is_closed: isClosed ? 1 : 0,
        created_at: now,
        updated_at: now,
      });
      operatingHourId += 1;
    }
  }
  await knex('operating_hours').insert(operatingHours);

  await knex('restaurant_addresses').insert([
    { id: 1, restaurant_id: 1, address_id: 7, is_primary: 1, is_pickup_point: 1, created_at: now, updated_at: now },
    { id: 2, restaurant_id: 2, address_id: 9, is_primary: 1, is_pickup_point: 1, created_at: now, updated_at: now },
    { id: 3, restaurant_id: 3, address_id: 10, is_primary: 1, is_pickup_point: 1, created_at: now, updated_at: now },
    { id: 4, restaurant_id: 1, address_id: 11, is_primary: 0, is_pickup_point: 0, created_at: now, updated_at: now },
  ]);

  await knex('delivery_zones').insert([
    { id: 1, restaurant_id: 1, name: 'Centro SP', zone_type: 'radius', radius_km: 5, minimum_order_value: 20, delivery_fee: 6.5, estimated_delivery_time_min: 40, is_active: 1, created_at: now, updated_at: now },
    { id: 2, restaurant_id: 1, name: 'Pinheiros', zone_type: 'radius', radius_km: 8, minimum_order_value: 30, delivery_fee: 9, estimated_delivery_time_min: 50, is_active: 1, created_at: now, updated_at: now },
    { id: 3, restaurant_id: 2, name: 'Zona Sul RJ', zone_type: 'radius', radius_km: 6, minimum_order_value: 40, delivery_fee: 10, estimated_delivery_time_min: 55, is_active: 1, created_at: now, updated_at: now },
    { id: 4, restaurant_id: 2, name: 'Ipanema Polygon', zone_type: 'polygon', polygon_geojson: '{"type":"Polygon","coordinates":[[[-43.205, -22.99],[-43.19,-22.99],[-43.19,-22.98],[-43.205,-22.98],[-43.205,-22.99]]]}', minimum_order_value: 45, delivery_fee: 12, estimated_delivery_time_min: 60, is_active: 1, created_at: now, updated_at: now },
    { id: 5, restaurant_id: 3, name: 'Centro BH', zone_type: 'radius', radius_km: 7, minimum_order_value: 25, delivery_fee: 7, estimated_delivery_time_min: 50, is_active: 1, created_at: now, updated_at: now },
    { id: 6, restaurant_id: 3, name: 'Bairro Lourdes', zone_type: 'radius', radius_km: 4, minimum_order_value: 30, delivery_fee: 9.5, estimated_delivery_time_min: 45, is_active: 0, created_at: now, updated_at: now },
  ]);

  await knex('categories').insert([
    { id: 1, restaurant_id: 1, name: 'Burgers', slug: 'burgers', sort_order: 1, is_active: 1, created_at: now, updated_at: now },
    { id: 2, restaurant_id: 1, name: 'Acompanhamentos', slug: 'acompanhamentos', sort_order: 2, is_active: 1, created_at: now, updated_at: now },
    { id: 3, restaurant_id: 1, name: 'Bebidas', slug: 'bebidas', sort_order: 3, is_active: 1, created_at: now, updated_at: now },
    { id: 4, restaurant_id: 1, name: 'Sobremesas', slug: 'sobremesas', sort_order: 4, is_active: 1, created_at: now, updated_at: now },
    { id: 5, restaurant_id: 2, name: 'Sushis', slug: 'sushis', sort_order: 1, is_active: 1, created_at: now, updated_at: now },
    { id: 6, restaurant_id: 2, name: 'Temakis', slug: 'temakis', sort_order: 2, is_active: 1, created_at: now, updated_at: now },
    { id: 7, restaurant_id: 2, name: 'Combinados', slug: 'combinados', sort_order: 3, is_active: 1, created_at: now, updated_at: now },
    { id: 8, restaurant_id: 2, name: 'Bebidas', slug: 'bebidas-r2', sort_order: 4, is_active: 1, created_at: now, updated_at: now },
    { id: 9, restaurant_id: 3, name: 'Pizzas Tradicionais', slug: 'pizzas-tradicionais', sort_order: 1, is_active: 1, created_at: now, updated_at: now },
    { id: 10, restaurant_id: 3, name: 'Pizzas Especiais', slug: 'pizzas-especiais', sort_order: 2, is_active: 1, created_at: now, updated_at: now },
    { id: 11, restaurant_id: 3, name: 'Bebidas', slug: 'bebidas-r3', sort_order: 3, is_active: 1, created_at: now, updated_at: now },
    { id: 12, restaurant_id: 3, name: 'Sobremesas', slug: 'sobremesas-r3', sort_order: 4, is_active: 1, created_at: now, updated_at: now },
  ]);

  await knex('products').insert([
    { id: 1, restaurant_id: 1, category_id: 1, name: 'Burger Classic', slug: 'burger-classic', description: 'Pao brioche, carne 160g e queijo.', sku: 'R1-BUR-001', base_price: 29.9, stock_control_enabled: 1, stock_quantity: 80, preparation_time_min: 20, sort_order: 1, is_active: 1, created_at: now, updated_at: now },
    { id: 2, restaurant_id: 1, category_id: 1, name: 'Burger Bacon', slug: 'burger-bacon', description: 'Com bacon crocante e molho da casa.', sku: 'R1-BUR-002', base_price: 34.9, stock_control_enabled: 1, stock_quantity: 60, preparation_time_min: 22, sort_order: 2, is_active: 1, created_at: now, updated_at: now },
    { id: 3, restaurant_id: 1, category_id: 2, name: 'Batata Rustica', slug: 'batata-rustica', sku: 'R1-ACC-001', base_price: 16.9, stock_control_enabled: 0, preparation_time_min: 12, sort_order: 1, is_active: 1, created_at: now, updated_at: now },
    { id: 4, restaurant_id: 1, category_id: 3, name: 'Refrigerante Lata', slug: 'refrigerante-lata', sku: 'R1-BEB-001', base_price: 7.5, stock_control_enabled: 1, stock_quantity: 200, preparation_time_min: 2, sort_order: 1, is_active: 1, created_at: now, updated_at: now },
    { id: 5, restaurant_id: 1, category_id: 4, name: 'Brownie com Sorvete', slug: 'brownie-com-sorvete', sku: 'R1-SOB-001', base_price: 18.5, stock_control_enabled: 1, stock_quantity: 30, preparation_time_min: 8, sort_order: 1, is_active: 1, created_at: now, updated_at: now },
    { id: 6, restaurant_id: 1, category_id: 1, name: 'Burger Veggie', slug: 'burger-veggie', sku: 'R1-BUR-003', base_price: 31.9, stock_control_enabled: 1, stock_quantity: 40, preparation_time_min: 18, sort_order: 3, is_active: 1, created_at: now, updated_at: now },
    { id: 7, restaurant_id: 2, category_id: 5, name: 'Sushi Salmon 8un', slug: 'sushi-salmon-8un', sku: 'R2-SUS-001', base_price: 39.9, stock_control_enabled: 0, preparation_time_min: 18, sort_order: 1, is_active: 1, created_at: now, updated_at: now },
    { id: 8, restaurant_id: 2, category_id: 5, name: 'Sushi Tuna 8un', slug: 'sushi-tuna-8un', sku: 'R2-SUS-002', base_price: 41.9, stock_control_enabled: 0, preparation_time_min: 18, sort_order: 2, is_active: 1, created_at: now, updated_at: now },
    { id: 9, restaurant_id: 2, category_id: 6, name: 'Temaki Salmon', slug: 'temaki-salmon', sku: 'R2-TMK-001', base_price: 27.9, stock_control_enabled: 0, preparation_time_min: 14, sort_order: 1, is_active: 1, created_at: now, updated_at: now },
    { id: 10, restaurant_id: 2, category_id: 6, name: 'Temaki Skin', slug: 'temaki-skin', sku: 'R2-TMK-002', base_price: 24.9, stock_control_enabled: 0, preparation_time_min: 14, sort_order: 2, is_active: 1, created_at: now, updated_at: now },
    { id: 11, restaurant_id: 2, category_id: 7, name: 'Combinado 30 Pecas', slug: 'combinado-30-pecas', sku: 'R2-CMB-001', base_price: 89.9, stock_control_enabled: 0, preparation_time_min: 30, sort_order: 1, is_active: 1, created_at: now, updated_at: now },
    { id: 12, restaurant_id: 2, category_id: 8, name: 'Cha Gelado', slug: 'cha-gelado', sku: 'R2-BEB-001', base_price: 9.5, stock_control_enabled: 1, stock_quantity: 120, preparation_time_min: 2, sort_order: 1, is_active: 1, created_at: now, updated_at: now },
    { id: 13, restaurant_id: 3, category_id: 9, name: 'Pizza Margherita', slug: 'pizza-margherita', sku: 'R3-PIZ-001', base_price: 52.9, stock_control_enabled: 0, preparation_time_min: 30, sort_order: 1, is_active: 1, created_at: now, updated_at: now },
    { id: 14, restaurant_id: 3, category_id: 9, name: 'Pizza Calabresa', slug: 'pizza-calabresa', sku: 'R3-PIZ-002', base_price: 56.9, stock_control_enabled: 0, preparation_time_min: 30, sort_order: 2, is_active: 1, created_at: now, updated_at: now },
    { id: 15, restaurant_id: 3, category_id: 10, name: 'Pizza Camarao', slug: 'pizza-camarao', sku: 'R3-ESP-001', base_price: 79.9, stock_control_enabled: 0, preparation_time_min: 35, sort_order: 1, is_active: 1, created_at: now, updated_at: now },
    { id: 16, restaurant_id: 3, category_id: 10, name: 'Pizza Burrata', slug: 'pizza-burrata', sku: 'R3-ESP-002', base_price: 73.9, stock_control_enabled: 0, preparation_time_min: 35, sort_order: 2, is_active: 1, created_at: now, updated_at: now },
    { id: 17, restaurant_id: 3, category_id: 11, name: 'Suco Natural', slug: 'suco-natural', sku: 'R3-BEB-001', base_price: 11.5, stock_control_enabled: 1, stock_quantity: 90, preparation_time_min: 5, sort_order: 1, is_active: 1, created_at: now, updated_at: now },
    { id: 18, restaurant_id: 3, category_id: 12, name: 'Pudim Artesanal', slug: 'pudim-artesanal', sku: 'R3-SOB-001', base_price: 14.9, stock_control_enabled: 1, stock_quantity: 35, preparation_time_min: 7, sort_order: 1, is_active: 1, created_at: now, updated_at: now },
  ]);

  await knex('product_images').insert(Array.from({ length: 18 }, (_, idx) => {
    const id = idx + 1;
    return {
      id,
      product_id: id,
      image_url: `https://picsum.photos/600/400?product-${id}`,
      sort_order: 1,
      is_primary: 1,
      created_at: now,
      updated_at: now,
    };
  }));

  await knex('addon_groups').insert([
    { id: 1, restaurant_id: 1, name: 'Queijos', description: 'Escolha ate 2 queijos', min_select: 0, max_select: 2, is_required: 0, is_active: 1, sort_order: 1, created_at: now, updated_at: now },
    { id: 2, restaurant_id: 1, name: 'Molhos', description: 'Escolha 1 molho', min_select: 1, max_select: 1, is_required: 1, is_active: 1, sort_order: 2, created_at: now, updated_at: now },
    { id: 3, restaurant_id: 2, name: 'Extras de Sushi', description: 'Complementos para sushi', min_select: 0, max_select: 3, is_required: 0, is_active: 1, sort_order: 1, created_at: now, updated_at: now },
    { id: 4, restaurant_id: 2, name: 'Molhos orientais', description: 'Molhos para temaki', min_select: 0, max_select: 2, is_required: 0, is_active: 1, sort_order: 2, created_at: now, updated_at: now },
    { id: 5, restaurant_id: 3, name: 'Borda recheada', description: 'Adicione borda', min_select: 0, max_select: 1, is_required: 0, is_active: 1, sort_order: 1, created_at: now, updated_at: now },
    { id: 6, restaurant_id: 3, name: 'Extras', description: 'Ingredientes extras', min_select: 0, max_select: 4, is_required: 0, is_active: 1, sort_order: 2, created_at: now, updated_at: now },
  ]);

  await knex('addons').insert([
    { id: 1, restaurant_id: 1, addon_group_id: 1, name: 'Cheddar', price_delta: 4.5, is_active: 1, sort_order: 1, created_at: now, updated_at: now },
    { id: 2, restaurant_id: 1, addon_group_id: 1, name: 'Prato', price_delta: 3.5, is_active: 1, sort_order: 2, created_at: now, updated_at: now },
    { id: 3, restaurant_id: 1, addon_group_id: 1, name: 'Gorgonzola', price_delta: 6, is_active: 1, sort_order: 3, created_at: now, updated_at: now },
    { id: 4, restaurant_id: 1, addon_group_id: 2, name: 'Maionese da casa', price_delta: 0, is_active: 1, sort_order: 1, created_at: now, updated_at: now },
    { id: 5, restaurant_id: 1, addon_group_id: 2, name: 'Barbecue', price_delta: 0, is_active: 1, sort_order: 2, created_at: now, updated_at: now },
    { id: 6, restaurant_id: 1, addon_group_id: 2, name: 'Mostarda e mel', price_delta: 1, is_active: 1, sort_order: 3, created_at: now, updated_at: now },
    { id: 7, restaurant_id: 2, addon_group_id: 3, name: 'Cream Cheese', price_delta: 2.5, is_active: 1, sort_order: 1, created_at: now, updated_at: now },
    { id: 8, restaurant_id: 2, addon_group_id: 3, name: 'Shimeji', price_delta: 5, is_active: 1, sort_order: 2, created_at: now, updated_at: now },
    { id: 9, restaurant_id: 2, addon_group_id: 3, name: 'Wasabi extra', price_delta: 1.5, is_active: 1, sort_order: 3, created_at: now, updated_at: now },
    { id: 10, restaurant_id: 2, addon_group_id: 4, name: 'Tare', price_delta: 0, is_active: 1, sort_order: 1, created_at: now, updated_at: now },
    { id: 11, restaurant_id: 2, addon_group_id: 4, name: 'Ponzu', price_delta: 0, is_active: 1, sort_order: 2, created_at: now, updated_at: now },
    { id: 12, restaurant_id: 2, addon_group_id: 4, name: 'Tarê picante', price_delta: 1, is_active: 1, sort_order: 3, created_at: now, updated_at: now },
    { id: 13, restaurant_id: 3, addon_group_id: 5, name: 'Borda Catupiry', price_delta: 9.9, is_active: 1, sort_order: 1, created_at: now, updated_at: now },
    { id: 14, restaurant_id: 3, addon_group_id: 5, name: 'Borda Cheddar', price_delta: 9.9, is_active: 1, sort_order: 2, created_at: now, updated_at: now },
    { id: 15, restaurant_id: 3, addon_group_id: 5, name: 'Borda Chocolate', price_delta: 12.9, is_active: 1, sort_order: 3, created_at: now, updated_at: now },
    { id: 16, restaurant_id: 3, addon_group_id: 6, name: 'Bacon', price_delta: 6.5, is_active: 1, sort_order: 1, created_at: now, updated_at: now },
    { id: 17, restaurant_id: 3, addon_group_id: 6, name: 'Palmito', price_delta: 5.5, is_active: 1, sort_order: 2, created_at: now, updated_at: now },
    { id: 18, restaurant_id: 3, addon_group_id: 6, name: 'Parmesao', price_delta: 4.5, is_active: 1, sort_order: 3, created_at: now, updated_at: now },
  ]);

  await knex('product_addon_groups').insert([
    { id: 1, product_id: 1, addon_group_id: 1, created_at: now, updated_at: now },
    { id: 2, product_id: 1, addon_group_id: 2, created_at: now, updated_at: now },
    { id: 3, product_id: 2, addon_group_id: 1, created_at: now, updated_at: now },
    { id: 4, product_id: 2, addon_group_id: 2, created_at: now, updated_at: now },
    { id: 5, product_id: 6, addon_group_id: 2, created_at: now, updated_at: now },
    { id: 6, product_id: 7, addon_group_id: 3, created_at: now, updated_at: now },
    { id: 7, product_id: 8, addon_group_id: 3, created_at: now, updated_at: now },
    { id: 8, product_id: 9, addon_group_id: 4, created_at: now, updated_at: now },
    { id: 9, product_id: 10, addon_group_id: 4, created_at: now, updated_at: now },
    { id: 10, product_id: 13, addon_group_id: 5, created_at: now, updated_at: now },
    { id: 11, product_id: 14, addon_group_id: 5, created_at: now, updated_at: now },
    { id: 12, product_id: 15, addon_group_id: 6, created_at: now, updated_at: now },
    { id: 13, product_id: 16, addon_group_id: 6, created_at: now, updated_at: now },
  ]);

  await knex('combos').insert([
    { id: 1, restaurant_id: 1, category_id: 1, name: 'Combo Duplo Burger', slug: 'combo-duplo-burger', description: '2 burgers + 2 bebidas', combo_price: 72.9, is_active: 1, available_from: new Date('2026-05-01T00:00:00.000Z'), created_at: now, updated_at: now },
    { id: 2, restaurant_id: 1, category_id: 2, name: 'Combo Familia Burger', slug: 'combo-familia-burger', description: '4 burgers + 2 batatas', combo_price: 149.9, is_active: 1, available_from: new Date('2026-05-01T00:00:00.000Z'), created_at: now, updated_at: now },
    { id: 3, restaurant_id: 2, category_id: 7, name: 'Combo Sushi 50', slug: 'combo-sushi-50', description: '50 pecas variadas', combo_price: 129.9, is_active: 1, available_from: new Date('2026-05-01T00:00:00.000Z'), created_at: now, updated_at: now },
    { id: 4, restaurant_id: 2, category_id: 6, name: 'Combo Temaki Casal', slug: 'combo-temaki-casal', description: '2 temakis + 2 bebidas', combo_price: 69.9, is_active: 1, available_from: new Date('2026-05-01T00:00:00.000Z'), created_at: now, updated_at: now },
    { id: 5, restaurant_id: 3, category_id: 9, name: 'Combo Pizza + Refri', slug: 'combo-pizza-refri', description: '1 pizza + 1 refri 2L', combo_price: 79.9, is_active: 1, available_from: new Date('2026-05-01T00:00:00.000Z'), created_at: now, updated_at: now },
    { id: 6, restaurant_id: 3, category_id: 10, name: 'Combo Premium', slug: 'combo-premium-pizza', description: '2 pizzas especiais', combo_price: 139.9, is_active: 0, available_from: new Date('2026-05-01T00:00:00.000Z'), available_until: new Date('2026-12-31T23:59:59.000Z'), created_at: now, updated_at: now },
  ]);

  await knex('combo_items').insert([
    { id: 1, combo_id: 1, product_id: 1, quantity: 2, min_quantity: 1, max_quantity: 2, created_at: now, updated_at: now },
    { id: 2, combo_id: 1, product_id: 4, quantity: 2, min_quantity: 1, max_quantity: 2, created_at: now, updated_at: now },
    { id: 3, combo_id: 2, product_id: 1, quantity: 2, min_quantity: 1, max_quantity: 3, created_at: now, updated_at: now },
    { id: 4, combo_id: 2, product_id: 2, quantity: 2, min_quantity: 1, max_quantity: 3, created_at: now, updated_at: now },
    { id: 5, combo_id: 2, product_id: 3, quantity: 2, min_quantity: 1, max_quantity: 2, created_at: now, updated_at: now },
    { id: 6, combo_id: 3, product_id: 7, quantity: 1, min_quantity: 1, max_quantity: 1, created_at: now, updated_at: now },
    { id: 7, combo_id: 3, product_id: 8, quantity: 1, min_quantity: 1, max_quantity: 1, created_at: now, updated_at: now },
    { id: 8, combo_id: 3, product_id: 9, quantity: 2, min_quantity: 1, max_quantity: 2, created_at: now, updated_at: now },
    { id: 9, combo_id: 4, product_id: 9, quantity: 1, min_quantity: 1, max_quantity: 1, created_at: now, updated_at: now },
    { id: 10, combo_id: 4, product_id: 10, quantity: 1, min_quantity: 1, max_quantity: 1, created_at: now, updated_at: now },
    { id: 11, combo_id: 5, product_id: 13, quantity: 1, min_quantity: 1, max_quantity: 1, created_at: now, updated_at: now },
    { id: 12, combo_id: 5, product_id: 17, quantity: 1, min_quantity: 1, max_quantity: 1, created_at: now, updated_at: now },
    { id: 13, combo_id: 6, product_id: 15, quantity: 1, min_quantity: 1, max_quantity: 1, created_at: now, updated_at: now },
    { id: 14, combo_id: 6, product_id: 16, quantity: 1, min_quantity: 1, max_quantity: 1, created_at: now, updated_at: now },
  ]);

  await knex('carts').insert([
    { id: 1, customer_user_id: 1, restaurant_id: 1, status: 'active', customer_notes: 'Sem cebola', expires_at: new Date('2026-05-20T23:59:59.000Z'), created_at: now, updated_at: now },
    { id: 2, customer_user_id: 2, restaurant_id: 2, status: 'converted', customer_notes: 'Pedido convertido em order', created_at: now, updated_at: now },
    { id: 3, customer_user_id: 3, restaurant_id: 3, status: 'abandoned', customer_notes: 'Nao finalizado', created_at: now, updated_at: now },
    { id: 4, customer_user_id: 4, restaurant_id: 1, status: 'active', created_at: now, updated_at: now },
  ]);

  await knex('cart_items').insert([
    { id: 1, cart_id: 1, product_id: 1, quantity: 2, unit_price: 29.9, customer_notes: 'Bem passado', created_at: now, updated_at: now },
    { id: 2, cart_id: 1, product_id: 3, quantity: 1, unit_price: 16.9, created_at: now, updated_at: now },
    { id: 3, cart_id: 2, product_id: 9, quantity: 2, unit_price: 27.9, created_at: now, updated_at: now },
    { id: 4, cart_id: 2, combo_id: 3, quantity: 1, unit_price: 129.9, created_at: now, updated_at: now },
    { id: 5, cart_id: 3, product_id: 14, quantity: 1, unit_price: 56.9, created_at: now, updated_at: now },
    { id: 6, cart_id: 4, product_id: 2, quantity: 1, unit_price: 34.9, created_at: now, updated_at: now },
    { id: 7, cart_id: 4, combo_id: 1, quantity: 1, unit_price: 72.9, created_at: now, updated_at: now },
    { id: 8, cart_id: 4, product_id: 4, quantity: 2, unit_price: 7.5, created_at: now, updated_at: now },
  ]);

  await knex('cart_item_addons').insert([
    { id: 1, cart_item_id: 1, addon_id: 1, quantity: 1, unit_price: 4.5, created_at: now, updated_at: now },
    { id: 2, cart_item_id: 1, addon_id: 4, quantity: 1, unit_price: 0, created_at: now, updated_at: now },
    { id: 3, cart_item_id: 3, addon_id: 10, quantity: 1, unit_price: 0, created_at: now, updated_at: now },
    { id: 4, cart_item_id: 5, addon_id: 13, quantity: 1, unit_price: 9.9, created_at: now, updated_at: now },
    { id: 5, cart_item_id: 6, addon_id: 2, quantity: 1, unit_price: 3.5, created_at: now, updated_at: now },
    { id: 6, cart_item_id: 6, addon_id: 5, quantity: 1, unit_price: 0, created_at: now, updated_at: now },
  ]);

  await knex('coupons').insert([
    { id: 1, restaurant_id: 1, code: 'PROMO10', discount_type: 'percentage', discount_value: 10, max_discount_amount: 20, min_order_value: 30, usage_limit_total: 300, usage_limit_per_user: 2, used_count: 2, starts_at: new Date('2026-01-01T00:00:00.000Z'), ends_at: new Date('2026-12-31T23:59:59.000Z'), is_active: 1, created_at: now, updated_at: now },
    { id: 2, restaurant_id: 1, code: 'FRETEGRATIS', discount_type: 'free_delivery', discount_value: 0, min_order_value: 50, usage_limit_total: 150, usage_limit_per_user: 1, used_count: 1, starts_at: new Date('2026-01-01T00:00:00.000Z'), ends_at: new Date('2026-10-31T23:59:59.000Z'), is_active: 1, created_at: now, updated_at: now },
    { id: 3, restaurant_id: 2, code: 'SUSHI20', discount_type: 'fixed_amount', discount_value: 20, min_order_value: 100, usage_limit_total: 100, usage_limit_per_user: 1, used_count: 1, starts_at: new Date('2026-01-01T00:00:00.000Z'), ends_at: new Date('2026-12-31T23:59:59.000Z'), is_active: 1, created_at: now, updated_at: now },
    { id: 4, restaurant_id: 2, code: 'TEMAKI15', discount_type: 'percentage', discount_value: 15, max_discount_amount: 30, min_order_value: 80, usage_limit_total: 120, usage_limit_per_user: 2, used_count: 0, starts_at: new Date('2026-01-01T00:00:00.000Z'), ends_at: new Date('2026-12-31T23:59:59.000Z'), is_active: 1, created_at: now, updated_at: now },
    { id: 5, restaurant_id: 3, code: 'PIZZA25', discount_type: 'fixed_amount', discount_value: 25, min_order_value: 120, usage_limit_total: 100, usage_limit_per_user: 1, used_count: 1, starts_at: new Date('2026-01-01T00:00:00.000Z'), ends_at: new Date('2026-12-31T23:59:59.000Z'), is_active: 1, created_at: now, updated_at: now },
    { id: 6, restaurant_id: 3, code: 'INATIVO5', discount_type: 'percentage', discount_value: 5, min_order_value: 50, usage_limit_total: 100, usage_limit_per_user: 1, used_count: 0, starts_at: new Date('2026-01-01T00:00:00.000Z'), ends_at: new Date('2026-02-01T00:00:00.000Z'), is_active: 0, created_at: now, updated_at: now },
  ]);

  await knex('orders').insert([
    {
      id: 1,
      order_number: 'ORD-2026-0001',
      customer_user_id: 1,
      restaurant_id: 1,
      delivery_address_id: 1,
      coupon_id: 1,
      cart_id: 1,
      order_type: 'delivery',
      status: 'delivered',
      payment_status: 'paid',
      subtotal_amount: 76.7,
      addons_amount: 4.5,
      discount_amount: 8.12,
      delivery_fee: 6.5,
      service_fee: 2,
      total_amount: 81.58,
      customer_notes: 'Tocar interfone 1201',
      restaurant_notes: 'Cliente recorrente',
      placed_at: new Date('2026-05-10T18:00:00.000Z'),
      confirmed_at: new Date('2026-05-10T18:02:00.000Z'),
      prepared_at: new Date('2026-05-10T18:25:00.000Z'),
      dispatched_at: new Date('2026-05-10T18:35:00.000Z'),
      delivered_at: new Date('2026-05-10T19:00:00.000Z'),
      created_at: now,
      updated_at: now,
    },
    {
      id: 2,
      order_number: 'ORD-2026-0002',
      customer_user_id: 2,
      restaurant_id: 2,
      delivery_address_id: 3,
      coupon_id: 3,
      cart_id: 2,
      order_type: 'delivery',
      status: 'out_for_delivery',
      payment_status: 'authorized',
      subtotal_amount: 185.7,
      addons_amount: 0,
      discount_amount: 20,
      delivery_fee: 10,
      service_fee: 3,
      total_amount: 178.7,
      placed_at: new Date('2026-05-14T12:20:00.000Z'),
      confirmed_at: new Date('2026-05-14T12:23:00.000Z'),
      prepared_at: new Date('2026-05-14T12:55:00.000Z'),
      dispatched_at: new Date('2026-05-14T13:05:00.000Z'),
      created_at: now,
      updated_at: now,
    },
    {
      id: 3,
      order_number: 'ORD-2026-0003',
      customer_user_id: 3,
      restaurant_id: 3,
      delivery_address_id: 4,
      coupon_id: 5,
      cart_id: null,
      order_type: 'delivery',
      status: 'canceled',
      payment_status: 'canceled',
      subtotal_amount: 56.9,
      addons_amount: 9.9,
      discount_amount: 0,
      delivery_fee: 7,
      service_fee: 2,
      total_amount: 75.8,
      customer_notes: 'Cancelar se demorar',
      cancellation_reason: 'Cliente solicitou cancelamento',
      placed_at: new Date('2026-05-12T19:00:00.000Z'),
      canceled_at: new Date('2026-05-12T19:12:00.000Z'),
      created_at: now,
      updated_at: now,
    },
    {
      id: 4,
      order_number: 'ORD-2026-0004',
      customer_user_id: 4,
      restaurant_id: 1,
      delivery_address_id: null,
      coupon_id: null,
      cart_id: 4,
      order_type: 'pickup',
      status: 'ready_for_pickup',
      payment_status: 'paid',
      subtotal_amount: 107.8,
      addons_amount: 3.5,
      discount_amount: 0,
      delivery_fee: 0,
      service_fee: 2,
      total_amount: 113.3,
      placed_at: new Date('2026-05-14T11:40:00.000Z'),
      confirmed_at: new Date('2026-05-14T11:42:00.000Z'),
      prepared_at: new Date('2026-05-14T12:10:00.000Z'),
      created_at: now,
      updated_at: now,
    },
    {
      id: 5,
      order_number: 'ORD-2026-0005',
      customer_user_id: 1,
      restaurant_id: 2,
      delivery_address_id: 2,
      coupon_id: null,
      cart_id: null,
      order_type: 'delivery',
      status: 'confirmed',
      payment_status: 'pending',
      subtotal_amount: 81.8,
      addons_amount: 2.5,
      discount_amount: 0,
      delivery_fee: 10,
      service_fee: 2,
      total_amount: 96.3,
      placed_at: new Date('2026-05-14T13:30:00.000Z'),
      confirmed_at: new Date('2026-05-14T13:31:00.000Z'),
      created_at: now,
      updated_at: now,
    },
    {
      id: 6,
      order_number: 'ORD-2026-0006',
      customer_user_id: 2,
      restaurant_id: 1,
      delivery_address_id: 3,
      coupon_id: 2,
      cart_id: null,
      order_type: 'delivery',
      status: 'placed',
      payment_status: 'pending',
      subtotal_amount: 42.4,
      addons_amount: 0,
      discount_amount: 6.5,
      delivery_fee: 0,
      service_fee: 1,
      total_amount: 36.9,
      placed_at: new Date('2026-05-14T14:00:00.000Z'),
      created_at: now,
      updated_at: now,
    },
    {
      id: 7,
      order_number: 'ORD-2026-0007',
      customer_user_id: 4,
      restaurant_id: 3,
      delivery_address_id: 5,
      coupon_id: null,
      cart_id: null,
      order_type: 'delivery',
      status: 'preparing',
      payment_status: 'paid',
      subtotal_amount: 130.8,
      addons_amount: 6.5,
      discount_amount: 0,
      delivery_fee: 7,
      service_fee: 2,
      total_amount: 146.3,
      placed_at: new Date('2026-05-14T15:00:00.000Z'),
      confirmed_at: new Date('2026-05-14T15:02:00.000Z'),
      created_at: now,
      updated_at: now,
    },
    {
      id: 8,
      order_number: 'ORD-2026-0008',
      customer_user_id: 3,
      restaurant_id: 2,
      delivery_address_id: 4,
      coupon_id: 4,
      cart_id: null,
      order_type: 'delivery',
      status: 'delivered',
      payment_status: 'paid',
      subtotal_amount: 99.4,
      addons_amount: 1,
      discount_amount: 15,
      delivery_fee: 10,
      service_fee: 2,
      total_amount: 97.4,
      placed_at: new Date('2026-05-09T18:20:00.000Z'),
      confirmed_at: new Date('2026-05-09T18:23:00.000Z'),
      prepared_at: new Date('2026-05-09T18:50:00.000Z'),
      dispatched_at: new Date('2026-05-09T19:00:00.000Z'),
      delivered_at: new Date('2026-05-09T19:25:00.000Z'),
      created_at: now,
      updated_at: now,
    },
  ]);

  await knex('order_items').insert([
    { id: 1, order_id: 1, product_id: 1, item_name_snapshot: 'Burger Classic', quantity: 2, unit_price: 29.9, total_price: 59.8, customer_notes: 'Sem cebola', created_at: now, updated_at: now },
    { id: 2, order_id: 1, product_id: 3, item_name_snapshot: 'Batata Rustica', quantity: 1, unit_price: 16.9, total_price: 16.9, created_at: now, updated_at: now },
    { id: 3, order_id: 2, product_id: 9, item_name_snapshot: 'Temaki Salmon', quantity: 2, unit_price: 27.9, total_price: 55.8, created_at: now, updated_at: now },
    { id: 4, order_id: 2, combo_id: 3, item_name_snapshot: 'Combo Sushi 50', quantity: 1, unit_price: 129.9, total_price: 129.9, created_at: now, updated_at: now },
    { id: 5, order_id: 3, product_id: 14, item_name_snapshot: 'Pizza Calabresa', quantity: 1, unit_price: 56.9, total_price: 56.9, created_at: now, updated_at: now },
    { id: 6, order_id: 4, product_id: 2, item_name_snapshot: 'Burger Bacon', quantity: 1, unit_price: 34.9, total_price: 34.9, created_at: now, updated_at: now },
    { id: 7, order_id: 4, combo_id: 1, item_name_snapshot: 'Combo Duplo Burger', quantity: 1, unit_price: 72.9, total_price: 72.9, created_at: now, updated_at: now },
    { id: 8, order_id: 5, product_id: 7, item_name_snapshot: 'Sushi Salmon 8un', quantity: 2, unit_price: 39.9, total_price: 79.8, created_at: now, updated_at: now },
    { id: 9, order_id: 5, product_id: 12, item_name_snapshot: 'Cha Gelado', quantity: 2, unit_price: 9.5, total_price: 19, created_at: now, updated_at: now },
    { id: 10, order_id: 6, product_id: 1, item_name_snapshot: 'Burger Classic', quantity: 1, unit_price: 29.9, total_price: 29.9, created_at: now, updated_at: now },
    { id: 11, order_id: 6, product_id: 4, item_name_snapshot: 'Refrigerante Lata', quantity: 2, unit_price: 7.5, total_price: 15, created_at: now, updated_at: now },
    { id: 12, order_id: 7, product_id: 13, item_name_snapshot: 'Pizza Margherita', quantity: 1, unit_price: 52.9, total_price: 52.9, created_at: now, updated_at: now },
    { id: 13, order_id: 7, product_id: 15, item_name_snapshot: 'Pizza Camarao', quantity: 1, unit_price: 79.9, total_price: 79.9, created_at: now, updated_at: now },
    { id: 14, order_id: 8, product_id: 11, item_name_snapshot: 'Combinado 30 Pecas', quantity: 1, unit_price: 89.9, total_price: 89.9, created_at: now, updated_at: now },
    { id: 15, order_id: 8, product_id: 12, item_name_snapshot: 'Cha Gelado', quantity: 1, unit_price: 9.5, total_price: 9.5, created_at: now, updated_at: now },
  ]);

  await knex('order_item_addons').insert([
    { id: 1, order_item_id: 1, addon_id: 1, addon_name_snapshot: 'Cheddar', quantity: 1, unit_price: 4.5, total_price: 4.5, created_at: now, updated_at: now },
    { id: 2, order_item_id: 3, addon_id: 10, addon_name_snapshot: 'Tare', quantity: 1, unit_price: 0, total_price: 0, created_at: now, updated_at: now },
    { id: 3, order_item_id: 5, addon_id: 13, addon_name_snapshot: 'Borda Catupiry', quantity: 1, unit_price: 9.9, total_price: 9.9, created_at: now, updated_at: now },
    { id: 4, order_item_id: 6, addon_id: 2, addon_name_snapshot: 'Prato', quantity: 1, unit_price: 3.5, total_price: 3.5, created_at: now, updated_at: now },
    { id: 5, order_item_id: 8, addon_id: 7, addon_name_snapshot: 'Cream Cheese', quantity: 1, unit_price: 2.5, total_price: 2.5, created_at: now, updated_at: now },
    { id: 6, order_item_id: 12, addon_id: 16, addon_name_snapshot: 'Bacon', quantity: 1, unit_price: 6.5, total_price: 6.5, created_at: now, updated_at: now },
    { id: 7, order_item_id: 14, addon_id: 11, addon_name_snapshot: 'Ponzu', quantity: 1, unit_price: 0, total_price: 0, created_at: now, updated_at: now },
    { id: 8, order_item_id: 14, addon_id: 12, addon_name_snapshot: 'Tare picante', quantity: 1, unit_price: 1, total_price: 1, created_at: now, updated_at: now },
  ]);

  await knex('payments').insert([
    { id: 1, order_id: 1, payment_method: 'pix', status: 'paid', provider_name: 'MockPay', provider_transaction_id: 'TX-0001', authorization_code: 'AUTH0001', amount: 81.58, currency: 'BRL', metadata: JSON.stringify({ qr_code: 'pix://mock/0001' }), paid_at: new Date('2026-05-10T18:05:00.000Z'), created_at: now, updated_at: now },
    { id: 2, order_id: 2, payment_method: 'credit_card', status: 'authorized', provider_name: 'MockPay', provider_transaction_id: 'TX-0002', authorization_code: 'AUTH0002', amount: 178.7, currency: 'BRL', metadata: JSON.stringify({ card_last4: '4242' }), created_at: now, updated_at: now },
    { id: 3, order_id: 3, payment_method: 'credit_card', status: 'canceled', provider_name: 'MockPay', provider_transaction_id: 'TX-0003', authorization_code: 'AUTH0003', amount: 75.8, currency: 'BRL', metadata: JSON.stringify({ reason: 'customer_cancel' }), created_at: now, updated_at: now },
    { id: 4, order_id: 4, payment_method: 'cash', status: 'paid', provider_name: 'LocalCash', amount: 113.3, currency: 'BRL', paid_at: new Date('2026-05-14T12:15:00.000Z'), created_at: now, updated_at: now },
    { id: 5, order_id: 5, payment_method: 'pix', status: 'pending', provider_name: 'MockPay', provider_transaction_id: 'TX-0005', amount: 96.3, currency: 'BRL', metadata: JSON.stringify({ expires_in: 900 }), created_at: now, updated_at: now },
    { id: 6, order_id: 6, payment_method: 'wallet', status: 'pending', provider_name: 'WalletMock', amount: 36.9, currency: 'BRL', created_at: now, updated_at: now },
    { id: 7, order_id: 7, payment_method: 'debit_card', status: 'paid', provider_name: 'MockPay', provider_transaction_id: 'TX-0007', authorization_code: 'AUTH0007', amount: 146.3, currency: 'BRL', paid_at: new Date('2026-05-14T15:05:00.000Z'), created_at: now, updated_at: now },
    { id: 8, order_id: 8, payment_method: 'credit_card', status: 'paid', provider_name: 'MockPay', provider_transaction_id: 'TX-0008', authorization_code: 'AUTH0008', amount: 97.4, currency: 'BRL', paid_at: new Date('2026-05-09T18:25:00.000Z'), created_at: now, updated_at: now },
  ]);

  await knex('coupon_redemptions').insert([
    { id: 1, coupon_id: 1, user_id: 1, order_id: 1, discount_amount: 8.12, redeemed_at: new Date('2026-05-10T18:00:00.000Z'), created_at: now, updated_at: now },
    { id: 2, coupon_id: 3, user_id: 2, order_id: 2, discount_amount: 20, redeemed_at: new Date('2026-05-14T12:20:00.000Z'), created_at: now, updated_at: now },
    { id: 3, coupon_id: 5, user_id: 3, order_id: 3, discount_amount: 0, redeemed_at: new Date('2026-05-12T19:00:00.000Z'), created_at: now, updated_at: now },
    { id: 4, coupon_id: 4, user_id: 3, order_id: 8, discount_amount: 15, redeemed_at: new Date('2026-05-09T18:20:00.000Z'), created_at: now, updated_at: now },
    { id: 5, coupon_id: 2, user_id: 2, order_id: 6, discount_amount: 6.5, redeemed_at: new Date('2026-05-14T14:00:00.000Z'), created_at: now, updated_at: now },
  ]);

  await knex('favorites').insert([
    { id: 1, user_id: 1, restaurant_id: 1, created_at: now, updated_at: now },
    { id: 2, user_id: 1, restaurant_id: 2, created_at: now, updated_at: now },
    { id: 3, user_id: 2, restaurant_id: 2, created_at: now, updated_at: now },
    { id: 4, user_id: 2, restaurant_id: 1, created_at: now, updated_at: now },
    { id: 5, user_id: 3, restaurant_id: 3, created_at: now, updated_at: now },
    { id: 6, user_id: 4, restaurant_id: 1, created_at: now, updated_at: now },
    { id: 7, user_id: 4, restaurant_id: 3, created_at: now, updated_at: now },
    { id: 8, user_id: 14, restaurant_id: 2, created_at: now, updated_at: now },
  ]);

  await knex('restaurant_reviews').insert([
    { id: 1, order_id: 1, restaurant_id: 1, user_id: 1, rating: 5, comment: 'Excelente burger e entrega rapida.', is_visible: 1, created_at: now, updated_at: now },
    { id: 2, order_id: 2, restaurant_id: 2, user_id: 2, rating: 4, comment: 'Sushi muito bom, chegou um pouco morno.', is_visible: 1, created_at: now, updated_at: now },
    { id: 3, order_id: 3, restaurant_id: 3, user_id: 3, rating: 2, comment: 'Pedido cancelado apos atraso.', is_visible: 1, created_at: now, updated_at: now },
    { id: 4, order_id: 4, restaurant_id: 1, user_id: 4, rating: 5, comment: 'Retirada no tempo certo.', is_visible: 1, created_at: now, updated_at: now },
    { id: 5, order_id: 8, restaurant_id: 2, user_id: 3, rating: 5, comment: 'Combinado excelente.', is_visible: 1, created_at: now, updated_at: now },
  ]);

  await knex('order_reviews').insert([
    { id: 1, order_id: 1, user_id: 1, delivery_rating: 5, packaging_rating: 5, overall_rating: 5, comment: 'Tudo perfeito.', created_at: now, updated_at: now },
    { id: 2, order_id: 2, user_id: 2, delivery_rating: 4, packaging_rating: 4, overall_rating: 4, comment: 'Bom no geral.', created_at: now, updated_at: now },
    { id: 3, order_id: 3, user_id: 3, delivery_rating: 1, packaging_rating: 3, overall_rating: 2, comment: 'Nao chegou como esperado.', created_at: now, updated_at: now },
    { id: 4, order_id: 4, user_id: 4, delivery_rating: null, packaging_rating: 5, overall_rating: 5, comment: 'Retirada muito eficiente.', created_at: now, updated_at: now },
    { id: 5, order_id: 8, user_id: 3, delivery_rating: 5, packaging_rating: 5, overall_rating: 5, comment: 'Entrega impecavel.', created_at: now, updated_at: now },
  ]);

  console.log('[seed] Base generosa criada com sucesso.');
  console.log('[seed] Usuarios: 15 | Restaurantes: 3 | Produtos: 18 | Pedidos: 8');
  console.log('[seed] Logins principais:');
  console.log('  owner@restaurante.com   -> Owner@123');
  console.log('  manager@restaurante.com -> Manager@123');
  console.log('  cliente@example.com     -> Cliente@123');
  console.log('  admin@example.com       -> Admin@123');
};
